version: '3.8'

services:
  frontend:
    build:
      context: ./Multisite-frontend
    ports:
      - "3000:80"  # Map port 3000 on the host to port 80 in the container
    depends_on:
      - backend

  backend:
    build:
      context: ./Multisite-backend
    ports:
      - "4000:4000"  # Map port 4000 on the host to port 4000 in the container
    environment:
      - NODE_ENV=development